spring:
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp

#spring.datasource.url=jdbc:mysql://localhost:3306/ams?useSSL=true
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

###datasource1
#spring.datasource.ams.driver-class-name = com.mysql.jdbc.Driver
#spring.datasource.ams.jdbc-url = jdbc:mysql://localhost:3306/ams?useUnicode=true&characterEncoding=utf-8&useSSL=true
#spring.datasource.ams.username = root
#spring.datasource.ams.password = 123456
###datasource2
#spring.datasource.ams1.driver-class-name = com.mysql.jdbc.Driver
#spring.datasource.ams1.jdbc-url = jdbc:mysql://localhost:3306/ams1?useUnicode=true&characterEncoding=utf-8&useSSL=true
#spring.datasource.ams1.username = root
#spring.datasource.ams1.password = 123456

# Mysql 1
mysql:
 datasource:
        ams:
          url: jdbc:mysql://localhost:3306/ams?useUnicode=true&characterEncoding=utf-8&useSSL=true
          username: root
          password: 123456

          minPoolSize: 3
          maxPoolSize: 25
          maxLifetime: 20000
          borrowConnectionTimeout: 30
          loginTimeout: 30
          maintenanceInterval: 60
          maxIdleTime: 60


        ams1:
          url: jdbc:mysql://localhost:3306/ams1?useUnicode=true&characterEncoding=utf-8&useSSL=true
          username: root
          password: 123456

          minPoolSize: 3
          maxPoolSize: 25
          maxLifetime: 20000
          borrowConnectionTimeout: 30
          loginTimeout: 30
          maintenanceInterval: 60
          maxIdleTime: 60


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params=count: countSql
  page-size-zero: true
logging:
  config: classpath:logback.xml
  pattern:
    console: |
  path: D:/nmyslog/ams